[package]
name = "bevy_arca"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { path = "../bevy", default-features = false, features = ["bevy_winit"] }
windows = { version = "0.58", features = [
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_WindowsAndMessaging",
] }

raw-window-handle = "0.6"
smallvec = "1"

[[example]]
name = "demo"
path = "examples/demo.rs"
